#! /bin/zsh

setopt ERR_EXIT NO_UNSET PIPE_FAIL XTRACE

git clone --depth=1 --branch 'release/5.8' 'https://github.com/apple/swift-docc.git' DocC
pushd DocC
git checkout 825d7a46fa2a76b314657f05bf978e0c389bab44
swift build
popd

git clone --depth=1 --branch 'release/5.8' 'https://github.com/apple/swift-docc-render-artifact.git' DocC-Render
pushd DocC-Render
git checkout 5693c43c5d931ad4db1bf54c888c395d7bce8fd2
popd

git clone --depth=1 --branch 'release/5.8' 'https://github.com/apple/swift-book.git' TSPL
pushd TSPL
git checkout 46e7fa820e26a37f40768fe8aa7c1abdcc44df2d

export PATH=../DocC/.build/arm64-apple-macosx/debug/:$PATH
export DOCC_HTML_DIR=../DocC-Render/dist/
which docc
./bin/publish-book
mv swift-book ../
popd

del DocC DocC-Render TSPL
